<?php

namespace Page;

class Constants {

	public static $user_name = 'ADMINUSER';
	public static $password = 'ADMINPASS';
	public static $image_name = 'test-data/images/test.jpg';
	public static $audio_name = 'test-data/music/mpthreetest.mp3';
	public static $video_name = 'test-data/videos/testmpfour.mp4';
	public static $comment_str = 'Test comment';
	public static $custom_css_value = '#buddypress #whats-new { height: 500px !important; overflow: hidden;}';
	public static $custom_css_empty_value = '';
	public static $num_of_media_per_page = '2';
	public static $num_of_media_per_page_on_activity = '2';
	public static $min_value = '1';
	public static $thumbnail_width = '150';
	public static $thumbnail_height = '150';
	public static $medium_width = '320';
	public static $medium_height = '240';
	public static $large_width = '700';
	public static $large_height = '0';
	public static $activity_video_player_width = '320';
	public static $activity_video_player_height = '240';
	public static $single_video_width = '500';
	public static $single_video_height = '480';
	public static $activity_music_player_width = '350';
	public static $single_music_player_width = '640';
	public static $img_quality_value = '80';
	public static $rtmedia_settings_url = '/wp-admin/admin.php?page=rtmedia-settings';
	public static $save_settings_button_bottom = '.rtm-button-container.bottom .rtmedia-settings-submit';
	public static $rtmedia_settings = '#toplevel_page_rtmedia-settings';
	public static $top_save_button = '.rtm-button-container.top input.rtmedia-settings-submit';
	public static $group_table_row = 'tbody#the-list tr#groups';
	public static $enable_user_group_checkbox = 'input[name="bp_components[groups]"]';
	public static $save_bp_settings = 'input#bp-admin-component-submit';
	public static $display_tab_url = '#rtmedia-display';
	public static $buddypress_tab_url = '#rtmedia-bp';
	public static $types_tab_url = '#rtmedia-types';
	public static $media_sizes_tab_url = '#rtmedia-sizes';
	public static $privacy_tab_url = '#rtmedia-privacy';
	public static $custom_css_tab_url = '#rtmedia-custom-css-settings';
	public static $other_settings_tab_url = '#rtmedia-general';
	public static $display_tab = 'a#tab-rtmedia-display';
	public static $buddypress_tab = 'a#tab-rtmedia-bp';
	public static $types_tab = 'a#tab-rtmedia-types';
	public static $media_sizes_tab = 'a#tab-rtmedia-sizes';
	public static $privacy_tab = 'a#tab-rtmedia-privacy';
	public static $custom_css_tab = 'a#tab-rtmedia-custom-css-settings';
	public static $other_settings_tab = 'a#tab-rtmedia-general';
	public static $str_comment_checkbox_label = 'Allow user to comment on uploaded media';
	public static $str_direct_uplaod_checkbox_label = 'Enable Direct Upload';
	public static $str_lightbox_checkbox_label = 'Use lightbox to display media';
	public static $num_of_media_perpage_label = 'Number of media per page';
	public static $str_masonary_checkbox_label = 'Enable Masonry Cascading grid layout';
	public static $str_media_display_pagination_label = 'Media display pagination option';
	public static $str_media_search_label = 'Enable gallery media search';
	public static $str_enable_media_in_pro_label = 'Enable media in profile';
	public static $str_enable_media_in_group_label = 'Enable media in group';
	public static $num_of_media_label_activity = 'Number of media items to show in activity stream';
	public static $str_enable_album_label = 'Organize media into albums';
	public static $str_media_notification_label = 'Enable media notification';
	public static $str_activity_media_like_label = 'Create activity for media likes';
	public static $str_activity_media_comment_label = 'Create activity for media comments';
	public static $str_media_upload_from_activity_label = 'Allow upload from activity stream';
	public static $str_media_in_comment_label = 'Enable media in comment';
	public static $str_show_album_desc_label = 'Show album description';
	public static $photo_label = 'Photo';
	public static $videoLabel = 'Video';
	public static $music_label = 'Music';
	public static $media_photo_label = 'Photo';
	public static $photo_thumbnail_label = 'Thumbnail';
	public static $photo_medium_label = 'Medium';
	public static $photo_large_label = 'Large';
	public static $activity_player_label = 'ActivityPlayer';
	public static $single_player_label = 'SinglePlayer';
	public static $featured_label = 'Featured';
	public static $img_quality_label = 'JPEG/JPG image quality (1-100)';
	public static $privacy_label = 'Enable privacy';
	public static $defaultPrivacyLabel = 'Default privacy';
	public static $privacy_user_override_label = 'Allow users to set privacy for their content';
	public static $default_style_label = 'rtMedia default styles';
	public static $custom_css_label = 'Paste your CSS code';
	public static $str_enable_json_data_label = 'Enable JSON API';
	public static $str_enable_usage_data_tracking_label = 'Allow usage data tracking';
	public static $adminbar_menu_label = 'Admin bar menu integration';
	public static $footer_link_label = 'Add a link to rtMedia in footer';
	public static $comment_checkbox = 'input[name="rtmedia-options[general_enableComments]"]';
	public static $directUploadCheckbox = 'input[name="rtmedia-options[general_direct_upload]"]';
	public static $lightbox_checkbox = 'input[name="rtmedia-options[general_enableLightbox]"]';
	public static $masonary_checkbox = 'input[name="rtmedia-options[general_masonry_layout]"]';
	public static $load_more_radio_button = 'input[value="load_more"]';
	public static $pagination_radio_button = 'input[value="pagination"]';
	public static $num_of_media_textbox = 'input[name="rtmedia-options[general_perPageMedia]"]';
	public static $media_search_checkbox = 'input[name="rtmedia-options[general_enableGallerysearch]"]';
	public static $enable_media_in_pro_checkbox = 'input[name="rtmedia-options[buddypress_enableOnProfile]"]';
	public static $enable_media_in_group_checkbox = 'input[name="rtmedia-options[buddypress_enableOnGroup]"]';
	public static $enable_album_checkbox = 'input[name="rtmedia-options[general_enableAlbums]"]';
	public static $media_notification_checkbox = 'input[name="rtmedia-options[buddypress_enableNotification]"]';
	public static $activity_media_like_checkbox = 'input[name="rtmedia-options[buddypress_mediaLikeActivity]"]';
	public static $activity_media_comment_checkbox = 'input[name="rtmedia-options[buddypress_mediaCommentActivity]"]';
	public static $media_upload_from_activity_checkbox = 'input[name="rtmedia-options[buddypress_enableOnActivity]"]';
	public static $num_of_media_textbox_activity = 'input[name="rtmedia-options[buddypress_limitOnActivity]"]';
	public static $media_in_comment_checkbox = 'input[name="rtmedia-options[buddypress_enableOnComment]"]';
	public static $media_button_in_comment = 'button.rtmedia-comment-media-upload';
	public static $upload_file_in_comment = 'div.rtm-media-single-comments div.moxie-shim.moxie-shim-html5 input[type=file]';
	public static $album_desc_checkbox = 'input[name="rtmedia-options[general_enableAlbums_description]"]';
	public static $photo_checkbox = 'input[name="rtmedia-options[allowedTypes_photo_enabled]"]';
	public static $video_checkbox = 'input[name="rtmedia-options[allowedTypes_video_enabled]"]';
	public static $music_checkbox = 'input[name="rtmedia-options[allowedTypes_music_enabled]"]';
	public static $thumbnail_width_textbox = 'input[name="rtmedia-options[defaultSizes_photo_thumbnail_width]"]';
	public static $thumbnail_height_textbox = 'input[name="rtmedia-options[defaultSizes_photo_thumbnail_height]"]';
	public static $thumbnail_crop_checkbox = 'input[name="rtmedia-options[defaultSizes_photo_thumbnail_crop]"]';
	public static $medium_width_textbox = 'input[name="rtmedia-options[defaultSizes_photo_medium_width]"]';
	public static $medium_height_textbox = 'input[name="rtmedia-options[defaultSizes_photo_medium_height]"]';
	public static $medium_crop_checkbox = 'input[name="rtmedia-options[defaultSizes_photo_medium_crop]"]';
	public static $large_width_textbox = 'input[name="rtmedia-options[defaultSizes_photo_large_width]"]';
	public static $large_height_textbox = 'input[name="rtmedia-options[defaultSizes_photo_large_height]"]';
	public static $large_crop_checkbox = 'input[name="rtmedia-options[defaultSizes_photo_large_crop]"]';
	public static $activity_video_width_textbox = 'input[name="rtmedia-options[defaultSizes_video_activityPlayer_width]"]';
	public static $activity_video_height_textbox = 'input[name="rtmedia-options[defaultSizes_video_activityPlayer_height]"]';
	public static $single_video_width_textbox = 'input[name="rtmedia-options[defaultSizes_video_singlePlayer_width]"]';
	public static $single_video_height_textbox = 'input[name="rtmedia-options[defaultSizes_video_singlePlayer_height]"]';
	public static $activity_music_width_textbox = 'input[name="rtmedia-options[defaultSizes_music_activityPlayer_width]"]';
	public static $single_music_width_textbox = 'input[name="rtmedia-options[defaultSizes_music_singlePlayer_width]"]';
	public static $featured_width_textbox = 'input[name="rtmedia-options[defaultSizes_featured_default_width]"]';
	public static $featured_height_textbox = 'input[name="rtmedia-options[defaultSizes_featured_default_height]"]';
	public static $img_quality_textbox = 'input[name="rtmedia-options[general_jpeg_image_quality]"]';
	public static $privacy_checkbox = 'input[name="rtmedia-options[privacy_enabled]"]';
	public static $private_radio_button = '.rtm-form-radio input[value="60"]';
	public static $logged_in_users_radio_button = '.rtm-form-radio input[value="20"]';
	public static $public_radio_button = '.rtm-form-radio input[value="0"]';
	public static $privacy_user_override_checkbox = 'input[name="rtmedia-options[privacy_userOverride]"]';
	public static $default_style_checkbox = 'input[name="rtmedia-options[styles_enabled]"]';
	public static $css_textarea = '.rtm-form-textarea';
	public static $css_text_area = 'span.rtm-field-wrap #rtmedia-custom-css';
	public static $enable_json_data_checkbox = 'input[name="rtmedia-options[rtmedia_enable_api]"]';
	public static $enable_usage_data_tracking_checkbox = 'input[name="rtmedia-options[general_AllowUserData]"]';
	public static $adminbar_menu_checkbox = 'input[name="rtmedia-options[general_showAdminMenu]"]';
	public static $footer_link_checkbox = 'input[name="rtmedia-options[rtmedia_add_linkback]"]';
	public static $photo_link = 'a#rtmedia-nav-item-photo';
	public static $video_link = 'a#rtmedia-nav-item-video';
	public static $music_link = 'a#rtmedia-nav-item-music';
	public static $thumbnail_selector = '.rtmedia-item-thumbnail img';
	public static $video_selector_single = 'div#rtm-mejs-video-container';
	public static $video_selector_activity = 'div.mejs-container.svg.wp-video-shortcode.mejs-video';
	public static $audio_selector_activity = 'div.mejs-container.svg.wp-audio-shortcode.mejs-audio';
	public static $audio_selector_single = 'div.mejs-container.svg.wp-audio-shortcode.mejs-audio';
	public static $close_button = '.rtm-mfp-close';
	public static $masonry_layout_xpath = '//*[@id="rtm-gallery-title-container"]/h2';
	public static $masonry_layout = 'ul.masonry';
	public static $rtmedia_adminbar = '#wp-admin-bar-rtMedia';
	public static $footer_link = '.rtmedia-footer-link';
	public static $load_more = 'a#rtMedia-galary-next';
	public static $pagination_pattern = '.rtm-pagination .rtmedia-page-no';
	public static $media_link_on_profile = 'a#user-media';
	public static $media_link_on_group = 'a#media';
	public static $media_album_link = 'a#rtmedia-nav-item-albums';
	public static $upload_button_on_activity_page = '.rtmedia-add-media-button';
	public static $privacy_dropdown = 'select#rtSelectPrivacy';
	public static $media_per_page_activity_selector = 'ul#activity-stream  > li:first-child ul li';
	public static $media_per_page_on_media_selector = 'ul.rtm-gallery-list li';
	public static $group_list_selector = 'div#groups-dir-list > ul#groups-list li';
	public static $create_group_link = 'ul li#group-create-nav';
	public static $create_group_tabs = 'div#group-create-tabs';
	public static $group_name_textbox = 'input#group-name';
	public static $group_desc_textarea = 'textarea#group-desc';
	public static $create_group_button = 'input#group-creation-create';
	public static $media_uplaod_button_on_comment = 'div button.rtmedia-comment-media-upload';
	public static $media_option_button = 'div.rtmedia-action-buttons';
	public static $add_album_button_link = 'ul.rtm-options li a.rtmedia-modal-link';
	public static $create_album_popup = 'div.rtmedia-popup';
	public static $album_name_textbox = 'input.rtm-input-medium';
	public static $create_album_button = 'button#rtmedia_create_new_album';
	public static $close_album_button = 'button.mfp-close';
	public static $first_album = 'ul.rtmedia-album-list li:nth-child(1)';
	public static $album_edit_link = 'a.rtmedia-edit';
	public static $albumDescTeaxtarea = 'textarea.rtmedia-desc-textarea';
	public static $save_album_button = 'input.rtmedia-save-album';
	public static $album_desc_selector = '.gallery-album-description';
	public static $scroll_selector = 'a#rtmedia-nav-item-albums';
	public static $media_page_scroll_pos = '#user-activity';   //Scroll position for activity and media pages
	public static $profile_picture = 'div#item-header-avatar';
	public static $comment_link = 'span > a.rtmedia-comment-link';
	public static $media_seach_selector = '.media_search';
	public static $activity_privacy_status = '#activity-stream.activity-list.item-list > li.activity.activity_update.activity-item > div.activity-content > div.activity-inner p';
	public static $comment_div = 'div.rtmedia-comment-content p';
	public static $go_back_to_album_page = 'a.rtm-button-back';
	public static $meta_section = '.widget_meta';
	public static $logout_link = '.widget_meta > ul > li:nth-child(2) a';
	public static $logout_msg = 'p.message';
	public static $save_session = false;
	public static $file_list = '#rtmedia_uploader_filelist';
	public static $site_entry_title = '.entry-title';
	public static $media_container = 'div.rtm-lightbox-container';
	public static $file_list_on_media_comment = 'div.rtmedia-plupload-notice';
	public static $save_msg_selector = '#setting-error-settings_updated';
	public static $next_group_button = '#group-creation-next';
	public static $manage_group_link = '#admin';
	public static $options_popup = '.rtm-options';
	public static $album_msg = ' album created successfully.';
	public static $activity_selector = '#activity-stream';
	
	public static $media_like_checkbox_label = 'Enable likes for media';
	public static $media_like_checkbox = 'input[name="rtmedia-options[general_enableLikes]"]';
	public static $like_button = '.rtmedia-like';

}
